# Generated by Django 4.2.3 on 2023-07-05 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[('Red', 'Red'), ('Green', 'Green'), ('Blue', 'Blue'), ('Yellow', 'Yellow'), ('Wild', 'Wild')], max_length=10)),
                ('value', models.CharField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), ('Skip', 'Skip'), ('Reverse', 'Reverse'), ('Draw2', 'Draw2'), ('Just', 'Just'), ('Draw4', 'Draw4')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('points', models.IntegerField(default=0)),
                ('hands', models.ManyToManyField(related_name='player_hand', to='api.card')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=255)),
                ('game_code', models.CharField(max_length=8)),
                ('num_players', models.IntegerField(default=10)),
                ('num_computers', models.IntegerField(default=0)),
                ('player_turn', models.IntegerField(null=True)),
                ('play_direction', models.IntegerField(default=1)),
                ('deck_cards', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deck_games', to='api.card')),
                ('discards', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discard_games', to='api.card')),
            ],
        ),
    ]
